### ISSUE TITLE
server防火牆規則設定

### ISSUE THREAD

**Issue by neko039** [isu-cisa/isu-credential#11]
設定iota_server02的防火牆規則(目前防火牆是關閉的)

**Comment by 1step2god** [comment]
@neko039 do you mean this firewall?
it is active now.

![螢幕快照 2020-09-03 下午3 52 45](https://user-images.githubusercontent.com/57473883/92087050-9c1ee280-edfd-11ea-92fc-f4eb24c4ea02.png)

**Comment by 1step2god** [comment]
@yillkid 140.127.196.91 ufw is on.
ufw status is same as 140.127.196.92 .

**Comment by neko039** [comment]
> @ neko039您的意思是這個防火牆嗎？
> 它現在處於活動狀態。
> 
> ![螢幕快照2020-09-03下午3 52 45](https://user-images.githubusercontent.com/57473883/92087050-9c1ee280-edfd-11ea-92fc-f4eb24c4ea02.png)

是這個防火牆沒錯

**Comment by 1step2god** [comment]
solved, close issue.

**Comment by neko039** [comment]
防火牆開起來後，http://140.127.196.92:5000/ 又連不進去了

**Comment by neko039** [comment]
@1step2god  我沒有說清楚，上次因為http://140.127.196.92:5000/ 連不進去，經過詢問是防火牆問題，所以俊毓學長才把防火牆關起來的，現在防火牆開起來後，又連不進去了

**Comment by 1step2god** [comment]
already allowed ufw port 5000.
