### ISSUE TITLE
使用 hash 編碼儲存密碼

### ISSUE THREAD

**Issue by yillkid** [isu-cisa/isu-credential#2]
目前的帳號儲存位置：/isu-credential/backend/static/accounts.txt

檔案內容：
``` json
{"account": "121212", "password": "12121"}
{"account": "121212", "password": "12121"}
```

key: password 欄位值必須要使用 hash 編碼

**Comment by neko039** [comment]
註冊流程:
輸入username、password-->將password+參數用SHA256加密成訊息摘要

accounts.txt內容:
username、參數、訊息摘要

登入流程:
輸入username、password-->用username找參數-->把password+參數用SHA256加密成訊息摘要-->與accounts.txt中的訊息摘要比對-->摘要相同就可以登入

流程應該是這樣對吧?參數是用來增加長度和攻擊難度的亂數，要設什麼?時間嗎? 
我想要確認一下我有沒有錯，再來寫程式 @yillkid @wcyang77
 
SHA256我找到python有一個叫hashlib的函數庫可以用，加密內容需要先使用encode()進行編碼。
https://blog.csdn.net/qq_38161040/article/details/103963756

**Comment by yillkid** [comment]
> 註冊流程:
> 輸入username、password-->將password+參數用SHA256加密成訊息摘要
> 
> accounts.txt內容:
> username、參數、訊息摘要
> 
> 登入流程:
> 輸入username、password-->用username找參數-->把password+參數用SHA256加密成訊息摘要-->與accounts.txt中的訊息摘要比對-->摘要相同就可以登入
> 
> 流程應該是這樣對吧?參數是用來增加長度和攻擊難度的亂數，要設什麼?時間嗎?
> 我想要確認一下我有沒有錯，再來寫程式 @yillkid @wcyang77
> 
> SHA256我找到python有一個叫hashlib的函數庫可以用，加密內容需要先使用encode()進行編碼。
> https://blog.csdn.net/qq_38161040/article/details/103963756

流程確認沒錯，再請您提交pull request，謝謝。

**Comment by neko039** [comment]
那哪個參數要設定什麼會比較好?還是其實不用?
@yillkid

**Comment by ShiFengZeng** [comment]
https://www.ithome.com.tw/voice/127918
https://stackoverflow.com/questions/9594125/salt-and-hash-a-password-in-python
參考看看。

**Comment by 1step2god** [comment]
@sen991113 登入密碼再加密做比對

**Comment by yillkid** [comment]
done.
