### ISSUE TITLE
架設老師審核頁面

### ISSUE THREAD

**Issue by sen991113** [isu-cisa/isu-credential#5]
程式碼編輯完成後會上傳，請後端協助架設。
@1step2god @neko039

**Comment by neko039** [comment]
測試版證書編輯器網址:http://140.127.196.92:5001/
測試版證書列表網址:http://140.127.196.92:5001/read_data

**Comment by neko039** [comment]
網頁存放位置 /workspace/isu-credential-beta/backend/templates

**Comment by 1step2god** [comment]
@sen991113 @mo724 
http://140.127.196.92:5000/verify_list
