### ISSUE TITLE
請問可以將其他網頁模板給我參考嗎?

### ISSUE THREAD

**Issue by mo724** [isu-cisa/isu-credential#51]
學長，上次你說可以和你說要網頁模板，請問可以傳給我嗎?
我需要參考模板獲得更多靈感  謝謝
@yillkid

**Comment by yillkid** [comment]
有蠻多免費的模板可以下載的，我建議您 `先挑選一個適合的` 。我再協助你套用進去。
參考：
- 例如這邊有[免費的 97 個模板](https://colorlib.com/wp/free-bootstrap-landing-pages-templates/)
- key word: bootstrap template
- [Google://bootstrap free template](https://www.google.com/search?q=bootstrap+free+template&oq=bootstrap+free&aqs=chrome.0.0j69i57j0l6.6295j0j7&sourceid=chrome&ie=UTF-8)

**Comment by 1step2god** [comment]
@mo724

**Comment by yillkid** [comment]
done
