### ISSUE TITLE
如何在背景持續運行網頁

### ISSUE THREAD

**Issue by sen991113** [isu-cisa/isu-credential#9]
學長，請問要在背景持續運行網頁該如何操作？

**Comment by yillkid** [comment]
> 學長，請問要在背景持續運行網頁該如何操作？

請問您有讀過這份文件了嗎？ [Docker 教學](https://hackmd.io/MmVZu_S2RuCTOExwZ4o2sA)

**Comment by neko039** [comment]
> > 學長，請問要在背景持續運行網頁該如何操作？
> 
> 請問您有讀過這份文件了嗎？[泊塢教學](https://hackmd.io/MmVZu_S2RuCTOExwZ4o2sA)

我已經有讀過文件了

**Comment by neko039** [comment]
我想要問一下dockfile是這樣寫嗎?
FROM python:3.6.9

WORKDIR /app

ADD . /app

RUN pip3 install -r requirements.txt

CMD python3 server.py

**Comment by yillkid** [comment]
> 我想要問一下dockfile是這樣寫嗎?
> FROM python:3.6.9
> 
> WORKDIR /app
> 
> ADD . /app
> 
> RUN pip3 install -r requirements.txt
> 
> CMD python3 server.py

打包成 image 跑一下不就知道了。XD

**Comment by 1step2god** [comment]
already make a dockerfile in this path ~/workspace/isu-credential/backend
but when I input code
`sudo docker build . -t docker-demo-app `

> Sending build context to Docker daemon  54.27kB
Step 1/5 : FROM python:3.6.9
 ---> 5bf410ee7bb2
Step 2/5 : WORKDIR /app
 ---> Using cache
 ---> 895fc55929fd
Step 3/5 : ADD . /app
 ---> 0af378083b46
Step 4/5 : RUN pip3 install -r requirements.txt
 ---> Running in 71820dc349b9

when machine run to this step, it report

> WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa2a05d8c18>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/flask/

> The command '/bin/sh -c pip3 install -r requirements.txt' returned a non-zero code: 1

how can I fix it? @yillkid

**Comment by yillkid** [comment]
這是因為 docker 環境內的 DNS 設定錯誤造成的。
我參照 [解決 Docker build pip install fail](https://blog.yowko.com/docker-build-pip-install-fail/) 這篇文章解決了問題。

```
$ sudo docker image ls
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
docker-demo-app      latest              7084382ec979        3 minutes ago       948MB
<none>               <none>              f6a6ab1fadde        2 hours ago         913MB
<none>               <none>              2ba5f9be12a6        2 hours ago         913MB
<none>               <none>              d2ac0d464020        2 hours ago         913MB
<none>               <none>              3464b11b080c        3 days ago          913MB
<none>               <none>              e559614648bf        3 days ago          913MB
gohornet/hornet      v0.5.0              002856e630e7        4 days ago          116MB
<none>               <none>              0af378083b46        4 days ago          913MB
<none>               <none>              b45a0ff1c41b        4 days ago          913MB
nginx                latest              4bb46517cac3        9 days ago          133MB
certbot/certbot      latest              994e18b9d74d        2 weeks ago         92.2MB
grafana/grafana      7.1.1               8df10701ce62        4 weeks ago         180MB
gohornet/hornet      v0.4.2              1265481a2332        4 weeks ago         117MB
prom/prometheus      v2.19.2             9f345bfa8fef        8 weeks ago         142MB
prom/alertmanager    v0.21.0             c876f5897d7b        2 months ago        55.5MB
prom/node-exporter   v1.0.1              0e0218889c33        2 months ago        26.4MB
haproxy              2.1.2               9b5ff4593b4e        6 months ago        92.3MB
hello-world          latest              bf756fb1ae65        7 months ago        13.3kB
python               3.6.9               5bf410ee7bb2        9 months ago        913MB
```

目前功能完全正常，我把 image 檔再刪除一次。
再請您重新編譯一次，謝謝。 :+1:

**Comment by 1step2god** [comment]
thanks, image package is done.

`docker run -p 3000:3000 -it a5ef5130e0d6`

there is another question, it report:

> docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.

is this issue about port 3000? I have to ask isu's office of informaion service to open port 3000?

**Comment by yillkid** [comment]
Thank you, could you push image to the [Docker Hub](https://hub.docker.com/) ?

**Comment by 1step2god** [comment]
have not Run Docker image as Cointainer yet,
when I input code
`docker run -p 3000:3000 -it a5ef5130e0d6`

it report:

> docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.

port 3000 did not open by isu's office of informaion service.
is this issue about port 3000? I have to ask isu's office of informaion service to open port 3000?

or I can push image to the Docker Hub first, then get back to fix  this problem?

**Comment by 1step2god** [comment]
140.127.196.92:5000/
Done!
